version: 2
jobs:
  build:
    working_directory: ~/kickstarter/laptop
    parallelism: 1
    # To see the list of pre-built images that CircleCI provides for most common languages see
    # https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6
    steps:
      - checkout
      - run:
          name: ShellCheck
          command: shellcheck mac
